export const tokenJapaneseNameMap = new Map([
  ["Treasure", "宝物"],
  ["Food", "食物"],
  ["Clue", "手掛かり"],
  ["Blood", "血"],
  ["Map", "地図"],
  ["Powerstone", "パワーストーン"],
  ["Copy", "コピー"],
  ["Copy token / copy marker", "コピー・トークン/コピー用マーカー"],
  ["Face-down / Manifest helper", "裏向き/予示用補助"],
  ["Drone", "ドローン"],
  ["Lander", "着陸船"],
  ["Faerie", "フェアリー"],
  ["Scion of the Deep", "深海の末裔"],
  ["Kithkin", "キスキン"],
  ["Detective", "探偵"],
  ["Skeleton Pirate", "スケルトン・海賊"],
  ["Skeleton", "スケルトン"],
  ["Ox", "雄牛"],
  ["Fractal", "フラクタル"],
  ["Inkling", "墨獣"],
  ["Mutagen", "ミュータジェン"],
  ["Golem", "ゴーレム"],
  ["Gnome", "ノーム"],
  ["Rat", "ネズミ"],
  ["Elf Warrior", "エルフ・戦士"],
  ["Army", "軍団"],
  ["Incubator", "培養器"],
  ["Fish", "魚"],
  ["Otter", "カワウソ"],
  ["Monk", "モンク"],
  ["Robot", "ロボット"],
  ["Drake", "ドレイク"],
  ["Soldier", "兵士"],
  ["Human Soldier", "人間・兵士"],
  ["Pilot", "操縦士"],
  ["Vehicle", "機体"],
  ["Ally", "同盟者"],
  ["Bat", "コウモリ"],
  ["Rabbit", "兎"],
  ["Wall", "壁"],
  ["Horror", "ホラー"],
  ["Toy", "玩具"],
  ["Warrior", "戦士"],
  ["Knight", "騎士"],
  ["Wizard", "ウィザード"],
  ["Rogue", "ならず者"],
  ["Samurai", "侍"],
  ["Ninja", "忍者"],
  ["Shark", "サメ"],
  ["Demon", "デーモン"],
  ["Angel", "天使"],
  ["Dragon", "ドラゴン"],
  ["Insect", "昆虫"],
  ["Saproling", "苗木"],
  ["Citizen", "市民"],
  ["Mercenary", "傭兵"],
  ["Mouse", "ハツカネズミ"],
  ["Raccoon", "アライグマ"],
  ["Lizard", "トカゲ"],
  ["Frog", "カエル"],
  ["Glimmer", "光霊"],
  ["Zombie", "ゾンビ"],
  ["Spirit", "スピリット"],
  ["Goblin", "ゴブリン"],
  ["Thopter", "飛行機械"],
  ["Bird", "鳥"],
  ["Cat", "猫"],
  ["Dog", "犬"],
  ["Beast", "ビースト"],
  ["Elemental", "エレメンタル"],
  ["Dinosaur", "恐竜"],
  ["Vampire", "吸血鬼"],
  ["Phyrexian", "ファイレクシアン"]
]);

export const defaultSources = {
  standard: [
    "https://www.hareruyamtg.com/ja/deck/",
    "https://article.hareruyamtg.com/article/?s=%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%80%E3%83%BC%E3%83%89",
    "https://mtg-jp.com/coverage/",
    "https://www.mtggoldfish.com/metagame/standard",
    "https://mtgdecks.net/Standard/decklists",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=ST",
    "https://www.mtgo.com/decklists"
  ],
  pioneer: [
    "https://www.hareruyamtg.com/ja/deck/",
    "https://article.hareruyamtg.com/article/?s=%E3%83%91%E3%82%A4%E3%82%AA%E3%83%8B%E3%82%A2",
    "https://mtg-jp.com/coverage/",
    "https://www.mtggoldfish.com/metagame/pioneer",
    "https://mtgdecks.net/Pioneer/decklists",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=PI",
    "https://www.mtgo.com/decklists"
  ],
  modern: [
    "https://www.hareruyamtg.com/ja/deck/",
    "https://article.hareruyamtg.com/article/?s=%E3%83%A2%E3%83%80%E3%83%B3",
    "https://mtg-jp.com/coverage/",
    "https://www.mtggoldfish.com/metagame/modern",
    "https://mtgdecks.net/Modern/decklists",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=MO",
    "https://www.mtgo.com/decklists"
  ],
  legacy: [
    "https://www.hareruyamtg.com/ja/deck/",
    "https://article.hareruyamtg.com/article/?s=%E3%83%AC%E3%82%AC%E3%82%B7%E3%83%BC",
    "https://mtg-jp.com/coverage/",
    "https://www.mtggoldfish.com/metagame/legacy",
    "https://mtgdecks.net/Legacy/decklists",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=LE",
    "https://www.mtgo.com/decklists"
  ]
};

export const formatEnvironmentEvents = {
  standard: [
    {
      date: "2025-07-25",
      affectsFormat: true,
      type: "rotation",
      title: "2025 Standard rotation at Edge of Eternities prerelease",
      reason: "Edge of Eternities prerelease caused Standard rotation for tabletop play.",
      sourceUrl: "https://magic.gg/news/metagame-mentor-the-winners-and-losers-from-standards-2025-rotation"
    },
    {
      date: "2026-04-24",
      affectsFormat: true,
      type: "set-release",
      title: "Secrets of Strixhaven tabletop release",
      reason: "Secrets of Strixhaven became Standard legal, adding a new Standard-legal set.",
      sourceUrl: "https://magic.wizards.com/en/news/feature/collecting-secrets-of-strixhaven"
    },
    {
      date: "2026-05-18",
      affectsFormat: false,
      type: "banned-restricted",
      title: "Banned and Restricted Announcement - May 18, 2026",
      reason: "The latest B&R announcement did not change Standard, so it is shown as context but does not reset the environment start.",
      sourceUrl: "https://magic.wizards.com/en/news/announcements/banned-and-restricted-may-18-2026"
    }
  ]
};
