export const tokenJapaneseNameMap = new Map([
  ["Treasure", "宝物"],
  ["Food", "食物"],
  ["Clue", "手掛かり"],
  ["Blood", "血"],
  ["Map", "地図"],
  ["Powerstone", "パワーストーン"],
  ["Copy", "コピー"],
  ["Copy token / copy marker", "コピー・トークン/コピー用マーカー"],
  ["Face-down / Manifest helper", "裏向き/予示用補助"],
  ["Drone", "ドローン"],
  ["Lander", "着陸船"],
  ["Faerie", "フェアリー"],
  ["Scion of the Deep", "深海の末裔"],
  ["Kithkin", "キスキン"],
  ["Detective", "探偵"],
  ["Skeleton Pirate", "スケルトン・海賊"],
  ["Skeleton", "スケルトン"],
  ["Ox", "雄牛"],
  ["Fractal", "フラクタル"],
  ["Inkling", "墨獣"],
  ["Mutagen", "ミュータジェン"],
  ["Golem", "ゴーレム"],
  ["Gnome", "ノーム"],
  ["Rat", "ネズミ"],
  ["Elf Warrior", "エルフ・戦士"],
  ["Army", "軍団"],
  ["Incubator", "培養器"],
  ["Fish", "魚"],
  ["Otter", "カワウソ"],
  ["Monk", "モンク"],
  ["Robot", "ロボット"],
  ["Drake", "ドレイク"],
  ["Soldier", "兵士"],
  ["Human Soldier", "人間・兵士"],
  ["Pilot", "操縦士"],
  ["Vehicle", "機体"],
  ["Ally", "同盟者"],
  ["Bat", "コウモリ"],
  ["Rabbit", "兎"],
  ["Wall", "壁"],
  ["Horror", "ホラー"],
  ["Toy", "玩具"],
  ["Warrior", "戦士"],
  ["Knight", "騎士"],
  ["Wizard", "ウィザード"],
  ["Rogue", "ならず者"],
  ["Samurai", "侍"],
  ["Ninja", "忍者"],
  ["Shark", "サメ"],
  ["Demon", "デーモン"],
  ["Angel", "天使"],
  ["Dragon", "ドラゴン"],
  ["Insect", "昆虫"],
  ["Saproling", "苗木"],
  ["Citizen", "市民"],
  ["Mercenary", "傭兵"],
  ["Mouse", "ハツカネズミ"],
  ["Raccoon", "アライグマ"],
  ["Lizard", "トカゲ"],
  ["Frog", "カエル"],
  ["Glimmer", "光霊"],
  ["Zombie", "ゾンビ"],
  ["Spirit", "スピリット"],
  ["Goblin", "ゴブリン"],
  ["Thopter", "飛行機械"],
  ["Bird", "鳥"],
  ["Cat", "猫"],
  ["Dog", "犬"],
  ["Beast", "ビースト"],
  ["Elemental", "エレメンタル"],
  ["Dinosaur", "恐竜"],
  ["Vampire", "吸血鬼"],
  ["Phyrexian", "ファイレクシアン"]
]);

export const defaultSources = {
  // 起点はメタゲームページ（条件に合ったデッキに絞り込み済み）のみ。
  // 記事・カバレージ系は日付フィルタが効かず古いデッキを拾うため除外。
  standard: [
    "https://www.hareruyamtg.com/ja/deck/1/metagame/",
    "https://www.mtggoldfish.com/metagame/standard",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=ST",
    "https://www.mtgo.com/decklists"
  ],
  pioneer: [
    "https://www.hareruyamtg.com/ja/deck/20/metagame/",
    "https://www.mtggoldfish.com/metagame/pioneer",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=PI",
    "https://www.mtgo.com/decklists"
  ],
  modern: [
    "https://www.hareruyamtg.com/ja/deck/2/metagame/",
    "https://www.mtggoldfish.com/metagame/modern",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=MO",
    "https://www.mtgo.com/decklists"
  ],
  legacy: [
    "https://www.hareruyamtg.com/ja/deck/3/metagame/",
    "https://www.mtggoldfish.com/metagame/legacy",
    "https://magic.gg/decklists",
    "https://mtgtop8.com/format?f=LE",
    "https://www.mtgo.com/decklists"
  ]
};

import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
export const formatEnvironmentEvents = require("../data/environment-events.json");
