import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fetchJson } from "./cache.js";
import { scryfallCacheTtlMs } from "./config.js";

// セット発売の環境イベントを Scryfall /sets から自動生成する。
// これにより data/environment-events.json に手書きするのは
// 禁止改定とローテーションだけになる（定期メンテの主要な事故源だった）。
const setsCachePath = resolve(".cache", "scryfall", "sets.json");

const SET_EVENT_FORMATS = ["standard", "pioneer", "modern", "legacy"];
const FORMAT_LABELS = { standard: "Standard", pioneer: "Pioneer", modern: "Modern", legacy: "Legacy" };

// 全構築フォーマットに新カードを加えるのは通常セット（expansion / core）のみ。
// Commander・Masters 等は Standard 環境を変えないため対象外（従来の手書き運用と同じ基準）。
function isEnvironmentSet(set) {
  return !set.digital
    && (set.set_type === "expansion" || set.set_type === "core")
    && Boolean(set.released_at);
}

function toSetEvent(set) {
  return {
    date: set.released_at,
    type: "set-release",
    title: `${set.name} tabletop release`,
    sourceUrl: set.scryfall_uri || "https://scryfall.com/sets",
    formatsAffected: [...SET_EVENT_FORMATS],
    changes: Object.fromEntries(
      SET_EVENT_FORMATS.map((format) => [format, `${set.name} became legal in ${FORMAT_LABELS[format]}.`])
    ),
    autoGenerated: true
  };
}

async function readSetsCache({ allowStale = false } = {}) {
  try {
    const raw = await readFile(setsCachePath, "utf8");
    const entry = JSON.parse(raw);
    if (!Array.isArray(entry?.sets)) return null;
    if (!allowStale && Date.now() > Number(entry.expiresAt || 0)) return null;
    return entry.sets;
  } catch {
    return null;
  }
}

async function writeSetsCache(sets) {
  await mkdir(dirname(join(setsCachePath)), { recursive: true });
  await writeFile(setsCachePath, JSON.stringify({
    fetchedAt: new Date().toISOString(),
    expiresAt: Date.now() + scryfallCacheTtlMs,
    sets
  }), "utf8");
}

export function setReleaseEventsFromSets(sets) {
  return (sets || []).filter(isEnvironmentSet).map(toSetEvent);
}

export async function fetchSetReleaseEvents() {
  const cached = await readSetsCache();
  if (cached) return setReleaseEventsFromSets(cached);

  try {
    let url = "https://api.scryfall.com/sets";
    const sets = [];
    while (url) {
      const data = await fetchJson(url);
      sets.push(...(data.data || []));
      url = data.has_more ? data.next_page : null;
    }
    await writeSetsCache(sets);
    return setReleaseEventsFromSets(sets);
  } catch (error) {
    // オフラインや Scryfall 障害では検索自体を止めず、期限切れキャッシュ→手書きイベントのみ、と段階的に縮退する
    const stale = await readSetsCache({ allowStale: true });
    if (stale) {
      console.log(`[sets] using stale set list: ${error.message}`);
      return setReleaseEventsFromSets(stale);
    }
    console.log(`[sets] set list unavailable (${error.message}); manual events only`);
    return [];
  }
}
